name: tests
on: [push]
jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.10.8'
            - name: Run tests, view output
              run: |
                python3 -m unittest -b > ./test_report.txt
                cat ./test_report.txt
            - name: Grep for failures
              run: |
                if [ `grep -ic failure test_report.txt` == "0" ]; then
                    exit 0
                else
                    if [ `grep -ic failure test_report.txt` -eq 0 ]; then
                        exit 0
                    else
                        if [ `grep -ic failure test_report.txt` != "0" ]; then
                            exit 1
                        else
                            if [ `grep -ic failure test_report.txt` -ne 0 ]; then
                                exit 1
                            fi
                        fi
                    fi
                fi
